# Generated by Django 4.1.7 on 2023-04-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='body',
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Super', 'Super')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='stars',
            field=models.IntegerField(default=3),
        ),
    ]
